finalized design, testers for welcome and home page
CSE-110-FA24-Team-17/SleepBuddies pull request #50
Opened 2024-11-19 23:18 UTC by jut008

2024-11-19 23:45 UTC, jut008 commented
i tried to make testers for the home page, but i cant seem to make it work because the buttons are images (running into a lot of errors, so i think we can skip home page testers tbh)

2024-11-20 00:14 UTC, jut008 commented
done! someone please review !

2024-11-20 00:53 UTC, Shuzhengz requested changes
Yoo looks very nice! However I think we should probably change the buttons on the home screen to some other color when hovered on, right now it's the same as background and that's a bit confusing for the users:

![image](https://github.com/user-attachments/assets/2c9eb9f9-4d37-416c-b3e5-15f3d53b65d6)

2024-11-20 00:53 UTC, Shuzhengz commented on client/src/components/pages/welcome.test.tsx
maybe we should put all tests into a dedicated dir smth like this:

![image](https://github.com/user-attachments/assets/43dc7f57-1ec7-421c-bb6f-2290d4491f12)

2024-11-20 00:53 UTC, Shuzhengz commented on client/src/components/pages/welcome.tsx
> +import React, { useEffect } from "react";
idt `React` is used

2024-11-20 00:58 UTC, jut008 commented on client/src/components/pages/welcome.test.tsx
got it!

2024-11-20 00:59 UTC, Shuzhengz commented on client/src/components/pages/alarm.tsx
not the best practice to modify files outside of scope, will cause merge conflicts to #43

2024-11-20 01:00 UTC, Shuzhengz commented on client/src/components/pages/alarm.tsx
prob wanna wait till #43 is merged before merging this to avoid conflicts :(

2024-11-20 01:01 UTC, Shuzhengz commented on client/src/components/pages/welcome.tsx
> +import React, { useEffect } from "react";
actually it might be better to keep it

2024-11-21 02:08 UTC, Shuzhengz approved these changes
Nice!

2024-11-22 04:50 UTC, Shuzhengz approved these changes
nice

2024-11-27 21:50 UTC, merged