Alarm Page Update
CSE-110-FA24-Team-17/SleepBuddies pull request #58
Opened 2024-11-22 21:31 UTC by JingtingL

Multiple Alarms, More User Modifiability

2024-11-22 21:34 UTC, JingtingL commented
Don't merge

2024-11-22 21:34 UTC, JingtingL commented
Still need to fix bug

2024-12-01 00:04 UTC, Shuzhengz commented on client/src/Alarm.test.tsx
put tests in `src/tests`

2024-12-04 00:46 UTC, JingtingL commented on client/src/Alarm.test.tsx
Ok

2024-12-04 02:32 UTC, Shuzhengz requested changes
merge conflicts

2024-12-04 05:29 UTC, JingtingL reviewed
no test here

2024-12-04 05:30 UTC, JingtingL reviewed
no test here

2024-12-04 12:43 UTC, Shuzhengz commented
the alarm on the homepage is broken, but i think we're changing the homepage layout so no need to fix this yet

![image](https://github.com/user-attachments/assets/2c28aa3b-0679-4183-97fd-ead832dd4362)

2024-12-04 12:47 UTC, Shuzhengz commented
I'm also not able to get the alarm to sound for some reason

2024-12-04 12:56 UTC, Shuzhengz approved these changes
doesn't seem like it is functional yet, but other than that the ux lgtm

o also prob add a remove alarm feature

2024-12-04 20:11 UTC, JingtingL commented
> I'm also not able to get the alarm to sound for some reason

Have you pull???

2024-12-04 20:13 UTC, JingtingL commented
Yup and there should be a remove alarm feature. Can you pull and send me what you see?

2024-12-04 20:15 UTC, Shuzhengz commented
> Have you pull? The alarm sound should be there, under directly under the public folder??? Can you check for me and see if you see it?

O that was from last night, I can take a look at it again a bit later

2024-12-04 20:19 UTC, JingtingL commented
Yeye I fixed it last night, not sure what happen sigh

2024-12-04 23:02 UTC, Shuzhengz approved these changes
Everything works now, lgtm!

2024-12-04 23:10 UTC, merged

2024-12-04 23:22 UTC, Shuzhengz commented on client/src/components/pages/alarm.tsx
> -    }, []);
@JingtingL i think this got deleted accidentally